# Generated by Django 6.1 on 2026-08-09 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoard', models.IntegerField(default=250)),
                ('day', models.IntegerField(default=1)),
                ('phase', models.CharField(choices=[('dawn', 'Dawn'), ('morning_parley', 'Morning parley'), ('moot', 'Moot'), ('dusk_parley', 'Dusk parley'), ('night', 'Night'), ('implementor', 'Implementor')], default='dawn', max_length=32)),
                ('wakes', models.IntegerField(default=0)),
                ('rage', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ended', 'Ended'), ('burned', 'Burned')], default='running', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('phase', models.CharField(choices=[('dawn', 'Dawn'), ('morning_parley', 'Morning parley'), ('moot', 'Moot'), ('dusk_parley', 'Dusk parley'), ('night', 'Night'), ('implementor', 'Implementor')], max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.game')),
            ],
        ),
        migrations.CreateModel(
            name='Thief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gold', models.IntegerField(default=0)),
                ('take_policy', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thieves', to='main.game')),
            ],
        ),
    ]
