# Generated by Django 6.1 on 2026-08-10 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_alter_user_first_name_event_thief'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='agents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thief',
            name='diary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='thief',
            name='persona',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DebateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('round', models.IntegerField()),
                ('text', models.TextField(blank=True, default='')),
                ('order', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_messages', to='main.game')),
                ('thief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_messages', to='main.thief')),
            ],
        ),
        migrations.CreateModel(
            name='Parley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('window', models.CharField(choices=[('morning', 'Morning'), ('dusk', 'Dusk')], max_length=32)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parleys', to='main.game')),
                ('opener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_parleys', to='main.thief')),
                ('participants', models.ManyToManyField(blank=True, related_name='parleys', to='main.thief')),
            ],
        ),
        migrations.CreateModel(
            name='ParleyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('text', models.TextField(blank=True, default='')),
                ('order', models.IntegerField()),
                ('parley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.parley')),
                ('thief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parley_messages', to='main.thief')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('floor', 'Floor'), ('failed', 'Failed'), ('passed', 'Passed'), ('law', 'Law')], default='submitted', max_length=32)),
                ('yes', models.IntegerField(default=0)),
                ('no', models.IntegerField(default=0)),
                ('abstain', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='main.thief')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='main.game')),
                ('seconded_by', models.ManyToManyField(blank=True, related_name='seconded_proposals', to='main.thief')),
            ],
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain')], max_length=32)),
                ('thief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='main.thief')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='main.proposal')),
            ],
        ),
    ]
