# Generated by Django 6.1 on 2026-08-10 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_game_agents_thief_diary_thief_persona_debatemessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, null=True)),
                ('phase', models.CharField(blank=True, choices=[('dawn', 'Dawn'), ('morning_parley', 'Morning parley'), ('moot', 'Moot'), ('dusk_parley', 'Dusk parley'), ('night', 'Night'), ('implementor', 'Implementor')], max_length=32, null=True)),
                ('purpose', models.CharField(blank=True, default='', max_length=100)),
                ('messages', models.JSONField(default=list)),
                ('response', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='main.game')),
                ('thief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='main.thief')),
            ],
        ),
    ]
