# Generated by Django 6.1 on 2026-08-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_llmcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='thief',
            name='goal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='thief',
            name='goal_condition',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='thief',
            name='goal_met_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thief',
            name='goal_payout',
            field=models.IntegerField(default=0),
        ),
    ]
