# Generated by Django 6.1 on 2026-08-10 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_thief_goal_thief_goal_condition_thief_goal_met_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='scratchpad',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('code', models.TextField()),
                ('scratchpad', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to='main.game')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to='main.proposal')),
            ],
            options={
                'ordering': ('day', 'pk'),
            },
        ),
    ]
