# Generated by Django 6.1 on 2026-08-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_game_scratchpad_ruleset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("floor", "Floor"),
                    ("failed", "Failed"),
                    ("passed", "Passed"),
                    ("law", "Law"),
                    ("void", "Void"),
                ],
                default="submitted",
                max_length=32,
            ),
        ),
    ]
