# Generated by Django 6.1 on 2026-08-11 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rulesets', to='main.proposal'),
        ),
    ]
